apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: n-tier-backend
          image:  "{{ .Values.image.backend.repository}}:{{ .Values.image.backend.tag }}"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: mysql-config
